version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True;
    ports:
      - '8080:80'
    volumes:
      - ./assets:/app/assets
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    extends:
      file: docker-compose-db.yml
      service: db

networks:
  default:
    name: ocr_network
