version: '3.8'
services:
  db:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      - ACCEPT_EULA=Y
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:1433'
    volumes:
      - ${DB_DATA_VOLUME_NAME}:/var/opt/mssql/data
      - ${DB_LOG_VOLUME_NAME}:/var/opt/mssql/log
      - ${DB_SECRETS_VOLUME_NAME}:/var/opt/mssql/secrets
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U ${DB_USER} -P "${DB_PASSWORD}" -Q "SELECT 1" || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

volumes:
  sqlserver_data:
    driver: local
  sqlserver_log:
    driver: local
