version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.development
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=${DB_NAME};User Id=${DB_USER};Password=${SA_PASSWORD};TrustServerCertificate=True;
    ports:
      - '8080:80'
    volumes:
      - ./${ASSET_PATH}:/app/${ASSET_PATH}
      - ${SECURE_PROMPT_PATH}:/app/Prompt
    networks:
      - ocr_network
    restart: unless-stopped
networks:
  ocr_network:
    external: true
