version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=${DB_HOST},${DB_PORT};Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True;
      - ASSET_PATH=${ASSET_PATH}
    ports:
      - '8080:80'
    volumes:
      - ./${ASSET_PATH}:/app/${ASSET_PATH}
    networks:
      - ocr_network
    restart: unless-stopped

networks:
  ocr_network:
    # external: true
    driver: bridge
